---
- hosts: all
  user: root
  vars_files:
   - domains.yml
  tasks:
   - when: ansible_os_family == "RedHat"
     include_vars: vars/el.yml
   - when: ansible_os_family == "Debian"
     include_vars: vars/deb.yml
   - include: tasks/install-letsencrypt.yml
   - include: tasks/configure-letsencrypt.yml
