# Install the letsencrypt configuration files
---
- name: Create the letsencrypt conf directory
  file: path=/etc/letsencrypt
        state=directory
        owner=root
        group=root
        mode=700

- name: Install certificate configuration
  template: src=letsencrypt_config.ini.j2
            dest=/etc/letsencrypt/{{ item.common }}.ini
            owner=root
            group=root
            mode=0600
  with_items: "{{ domains }}"
