---
- name: Update SSLCertificateFile directive
  when: apache
  replace: dest={{ apache_vhost_path }}/{{ item.key }}.conf
           regexp="(\s+)SSLCertificateFile.*$"
           replace="\1SSLCertificateFile      /etc/letsencrypt/live/{{ item.key }}/cert.pem"
           backup=yes
           follow=yes
  with_dict: "{{ domains }}"
- name: Update SSLCertificateKeyFile directive
  when: apache
  replace: dest={{ apache_vhost_path }}/{{ item.key }}.conf
           regexp="(\s+)SSLCertificateKeyFile.*$"
           replace="\1SSLCertificateKeyFile   /etc/letsencrypt/live/{{ item.key }}/privkey.pem"
           backup=yes
           follow=yes
  with_dict: "{{ domains }}"
- name: Update SSLCertificateChainFile directive
  when: apache
  replace: dest={{ apache_vhost_path }}/{{ item.key }}.conf
           regexp="(\s+)SSLCertificateChainFile.*$"
           replace="\1SSLCertificateChainFile /etc/letsencrypt/live/{{ item.key }}/chain.pem"
           backup=yes
           follow=yes
  with_dict: "{{ domains }}"

